version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always
    ports:
      - 5433:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      TZ: UTC
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog
    container_name: demo-mail
    restart: always
    ports:
      - 8025:8025

volumes:
  keycloak_data: