version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: user_db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
volumes:
  user_data: